version: '2'
services:
  zookeeper:
    image: kakicode/zookeeper
    container_name: zookeeper
    ports:
      - "2181:2181"
      - "2888:2888"
      - "3888:3888"
  kafka:
    image: kakicode/kafka
    container_name: kafka
    depends_on: 
      - zookeeper
    links:
      - "zookeeper:zookeeper"
    ports:
      - "9092:9092"
  influxdb:
    image: kakicode/influxdb
    container_name: influxdb
    ports:
      - "8086:8086"
    volumes:
      - /tmp:/var/lib/influxdb
  flume:
    image: kakicode/flume
    container_name: flume
    depends_on: 
      - kafka
    links:
      - "zookeeper:zookeeper"
      - "influxdb:influxdb"
    environment:
      - DEBUG_PORT=6006
      - AGENT_NAME=kaki-agent
    ports:
      - "6006:6006"
  streams:
    image: kakicode/streams
    container_name: streams
    depends_on: 
      - kafka
    links:
      - "kafka:kafka"
      - "zookeeper:zookeeper"
    environment:
      - DEBUG_PORT=6008
      - KAFKA_CONFIG=kafka:9092
    ports:
      - "6008:6008"
  grafana:
    image: kakicode/grafana
    container_name: grafana
    depends_on: 
      - influxdb
    links:
      - "influxdb:influxdb"
    environment:
      - GF_SECURITY_ADMIN_USER=root
      - GF_SECURITY_ADMIN_PASSWORD=password
    ports:
      - "3000:3000"
